modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="le_mwd_smp"
version="1.0.0"
displayName="Le MWD SMP"
credits="Made with mcreator - https://mcreator.net/about"
displayURL="https://github.com/Gnawmon/LeMWDSMP"
authors="Liminal, Unnatural, Mark101, Gnawmon, Marioood, AndrewIdot, GameMasterPDX, Bolternon"
description='''
Its combination of minecraft args in a mod.
'''

[[dependencies.le_mwd_smp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




